/** Files generated by the demo prefill (src/lib/samples.ts), as opposed to files the user chose. */
const generated = new WeakSet<File>();
export const tagSampleFile = (f: File) => { generated.add(f); return f; };
export const isSampleFile = (f: File | null | undefined) => !!f && generated.has(f);
